name 'purplehazech-ccache'
version '0.2.0'

author 'Lucas S. Bickel'
license 'GNU Affero General Public License, version 3'
project_page 'https://github.com/purplehazech/puppet-ccache'
source 'git://github.com/purplehazech/puppet-ccache.git'
summary 'Gentoo Puppet Ccache Install'
description 'Installs ccache via puppet under gentoo.'
dependency 'puppetlabs/stdlib', '~3.2.0'
